# This file is a template, and might need editing before it works on your project.
# Full project: https://gitlab.com/pages/plain-html
pages:
	# image: node:latest
	image: node:10.15.3
	stage: deploy
	script:
	- npm install --progress=false
	- npm run gitlab
	- rm -rf public
	- mkdir public
	- cp -r build/* public
	artifacts:
		expire_in: 2 weeks
		paths:
		- public
	only:
	- master