# This file is a template, and might need editing before it works on your project.
# Full project: https://gitlab.com/pages/plain-html
pages:
  # image: node:latest
  image: node:8.9.1
  stage: deploy
  script:
  - npm install --progress=false
  - npm run build
  - rm -rf public
  - mkdir public
  - cp -r dist/* public
  artifacts:
    expire_in: 2 weeks
    paths:
    - public
  only:
  - master